#!/bin/bash
# MusicBrainz Mirror Bootstrap Script
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/OpenHomeFoundation/musicbrainz-docker-local/main/bootstrap.sh | bash
#   OR
#   wget -qO- https://raw.githubusercontent.com/OpenHomeFoundation/musicbrainz-docker-local/main/bootstrap.sh | bash
#
# This script will:
#   1. Clone the official musicbrainz-docker repository
#   2. Download the OHF local configuration
#   3. Create a .env file with your settings
#   4. Optionally run the installation script

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo "================================================="
echo "  MusicBrainz Mirror Bootstrap"
echo "  Open Home Foundation Configuration"
echo "================================================="
echo ""

# Configuration
MUSICBRAINZ_DOCKER_REPO="https://github.com/metabrainz/musicbrainz-docker.git"
MUSICBRAINZ_DOCKER_VERSION="v-2026-01-19.0"
OHF_LOCAL_REPO="https://github.com/OpenHomeFoundation/musicbrainz-docker-local.git"
INSTALL_DIR="${INSTALL_DIR:-$HOME/musicbrainz-docker}"

# Check for required commands
if ! command -v git &> /dev/null; then
    printf "${RED}Error: git is not installed${NC}\n"
    exit 1
fi

if ! command -v docker &> /dev/null; then
    printf "${YELLOW}Docker is not installed${NC}\n"
    read -p "Would you like to install Docker now? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Installing Docker..."
        curl -fsSL https://get.docker.com | sh
        if [ $? -ne 0 ]; then
            printf "${RED}Failed to install Docker${NC}\n"
            exit 1
        fi
        printf "${GREEN}✓${NC} Docker installed successfully\n"
    else
        printf "${RED}Docker is required. Please install it manually:${NC}\n"
        echo "  curl -fsSL https://get.docker.com | sh"
        exit 1
    fi
fi

# Check if Docker Compose is available
if ! docker compose version &> /dev/null; then
    printf "${RED}Error: Docker Compose is not installed${NC}\n"
    echo "Docker Compose v2 is required (comes with Docker Desktop or docker-compose-plugin)"
    exit 1
fi

printf "${GREEN}✓${NC} Prerequisites check passed\n"
echo ""

# Ask for installation directory
read -p "Installation directory [$INSTALL_DIR]: " input_dir
INSTALL_DIR="${input_dir:-$INSTALL_DIR}"

# Check if directory already exists
if [ -d "$INSTALL_DIR" ]; then
    printf "${YELLOW}Warning: Directory $INSTALL_DIR already exists${NC}\n"
    read -p "Remove and reinstall? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$INSTALL_DIR"
    else
        echo "Installation cancelled."
        exit 1
    fi
fi

# Step 1: Clone official musicbrainz-docker
echo ""
echo "================================================="
echo "Step 1: Cloning official musicbrainz-docker"
echo "================================================="
echo ""

git clone "$MUSICBRAINZ_DOCKER_REPO" "$INSTALL_DIR"
cd "$INSTALL_DIR"
git checkout "$MUSICBRAINZ_DOCKER_VERSION"
printf "${GREEN}✓${NC} Cloned musicbrainz-docker ($MUSICBRAINZ_DOCKER_VERSION)\n"

# Step 2: Clone OHF local configuration
echo ""
echo "================================================="
echo "Step 2: Downloading OHF configuration"
echo "================================================="
echo ""

cd "$INSTALL_DIR"

# Remove existing local folder (official repo has an empty one)
if [ -d "local" ]; then
    rm -rf local
fi

git clone "$OHF_LOCAL_REPO" local
printf "${GREEN}✓${NC} Downloaded OHF local configuration\n"

# Step 3: Configure environment
echo ""
echo "================================================="
echo "Step 3: Environment Configuration"
echo "================================================="
echo ""

read -p "Enter your domain name (e.g., musicbrainz.example.com): " DOMAIN
while [ -z "$DOMAIN" ]; do
    printf "${RED}Domain is required${NC}\n"
    read -p "Enter your domain name: " DOMAIN
done

echo ""
printf "${YELLOW}Note: You will need to add your SSL certificate to .env${NC}\n"
echo "Base64 encode your certificate and key files"

# Create .env file
cat > .env << EOF
# MusicBrainz Docker Configuration
# Generated by bootstrap.sh on $(date)

# Domain Configuration
MUSICBRAINZ_DOMAIN=$DOMAIN
MUSICBRAINZ_WEB_SERVER_HOST=$DOMAIN
MUSICBRAINZ_WEB_SERVER_PORT=443

# SSL Certificate (Base64 Encoded)
# Encode with: cat cert.pem | base64 -w0
#
# To encode your certificates:
#   cat cert.pem | base64 -w0      # Linux
#   cat cert.pem | base64 | tr -d '\n'   # macOS
#
# Paste the base64 string below (must be a single line)
SSL_CERTIFICATE_BASE64=PASTE_YOUR_BASE64_ENCODED_CERTIFICATE_HERE
SSL_CERTIFICATE_KEY_BASE64=PASTE_YOUR_BASE64_ENCODED_PRIVATE_KEY_HERE

# Compose file chain (loads OHF optimizations)
COMPOSE_FILE=docker-compose.yml:local/docker-compose.ohf.yml
EOF

printf "${GREEN}✓${NC} Created .env configuration file\n"

# Step 4: Summary and next steps
echo ""
echo "================================================="
echo "Setup Complete!"
echo "================================================="
echo ""
echo "Installation directory: $INSTALL_DIR"
echo "Domain: $DOMAIN"
echo ""
echo "Directory structure:"
echo "  $INSTALL_DIR/"
echo "  ├── docker-compose.yml"
echo "  ├── .env"
echo "  └── local/"
echo "      ├── docker-compose.ohf.yml"
echo "      ├── install.sh"
echo "      └── config/"
echo ""

# Ask to run install script
echo "The install script (for Ubuntu servers) will:"
echo "  - Configure UFW firewall"
echo "  - Apply system optimizations"
echo "  - Optionally start services"
echo ""
printf "${YELLOW}Note: install.sh is designed for Ubuntu servers.${NC}\n"
echo "If you're setting this up locally to deploy elsewhere, skip this step."
echo ""
read -p "Run the installation script now? (requires sudo, Ubuntu only) (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    sudo "$INSTALL_DIR/local/install.sh"
fi

echo ""
echo "================================================="
echo "Next Steps"
echo "================================================="
echo ""
echo "1. Base64 encode and add your SSL certificate to .env:"
echo "   cat cert.pem | base64 -w0  # copy output to SSL_CERTIFICATE_BASE64"
echo "   cat key.pem | base64 -w0   # copy output to SSL_CERTIFICATE_KEY_BASE64"
echo "   nano $INSTALL_DIR/.env"
echo ""
echo "2. Ensure your domain DNS points to your server"
echo ""
echo "3. Start services:"
echo "   cd $INSTALL_DIR"
echo "   docker compose up -d"
echo ""
echo "4. Verify HTTPS is working:"
echo "   curl -k https://localhost/health"
echo ""

echo "For documentation, see:"
echo "  - $INSTALL_DIR/local/README.md"
echo ""
