#!/bin/bash
# MusicBrainz Mirror Bootstrap Script
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/OpenHomeFoundation/musicbrainz-docker-local/main/bootstrap.sh | bash
#   OR
#   wget -qO- https://raw.githubusercontent.com/OpenHomeFoundation/musicbrainz-docker-local/main/bootstrap.sh | bash
#
# This script will:
#   1. Clone the official musicbrainz-docker repository
#   2. Download the OHF local configuration
#   3. Create a .env file with your settings
#   4. Optionally run the installation script

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo ""
echo "================================================="
echo "  MusicBrainz Mirror Bootstrap"
echo "  Open Home Foundation Configuration"
echo "================================================="
echo ""

# Configuration
MUSICBRAINZ_DOCKER_REPO="https://github.com/metabrainz/musicbrainz-docker.git"
MUSICBRAINZ_DOCKER_VERSION="v-2026-01-19.0"
OHF_LOCAL_REPO="https://github.com/OpenHomeFoundation/musicbrainz-docker-local.git"
INSTALL_DIR="${INSTALL_DIR:-$HOME/musicbrainz-docker}"

# Check for required commands
for cmd in git docker; do
    if ! command -v $cmd &> /dev/null; then
        echo -e "${RED}Error: $cmd is not installed${NC}"
        if [ "$cmd" = "docker" ]; then
            echo "Install Docker with: curl -fsSL https://get.docker.com | sh"
        fi
        exit 1
    fi
done

# Check if Docker Compose is available
if ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed${NC}"
    echo "Docker Compose v2 is required (comes with Docker Desktop or docker-compose-plugin)"
    exit 1
fi

echo -e "${GREEN}✓${NC} Prerequisites check passed"
echo ""

# Ask for installation directory
read -p "Installation directory [$INSTALL_DIR]: " input_dir
INSTALL_DIR="${input_dir:-$INSTALL_DIR}"

# Check if directory already exists
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}Warning: Directory $INSTALL_DIR already exists${NC}"
    read -p "Remove and reinstall? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$INSTALL_DIR"
    else
        echo "Installation cancelled."
        exit 1
    fi
fi

# Step 1: Clone official musicbrainz-docker
echo ""
echo "================================================="
echo "Step 1: Cloning official musicbrainz-docker"
echo "================================================="
echo ""

git clone "$MUSICBRAINZ_DOCKER_REPO" "$INSTALL_DIR"
cd "$INSTALL_DIR"
git checkout "$MUSICBRAINZ_DOCKER_VERSION"
echo -e "${GREEN}✓${NC} Cloned musicbrainz-docker ($MUSICBRAINZ_DOCKER_VERSION)"

# Step 2: Clone OHF local configuration
echo ""
echo "================================================="
echo "Step 2: Downloading OHF configuration"
echo "================================================="
echo ""

cd "$INSTALL_DIR"

# Remove existing local folder (official repo has an empty one)
if [ -d "local" ]; then
    rm -rf local
fi

git clone "$OHF_LOCAL_REPO" local
echo -e "${GREEN}✓${NC} Downloaded OHF local configuration"

# Step 3: Configure environment
echo ""
echo "================================================="
echo "Step 3: Environment Configuration"
echo "================================================="
echo ""

read -p "Enter your domain name (e.g., musicbrainz.example.com): " DOMAIN
while [ -z "$DOMAIN" ]; do
    echo -e "${RED}Domain is required${NC}"
    read -p "Enter your domain name: " DOMAIN
done

read -p "Enter your email (for Let's Encrypt notifications): " EMAIL
while [ -z "$EMAIL" ]; do
    echo -e "${RED}Email is required${NC}"
    read -p "Enter your email: " EMAIL
done

# Create .env file
cat > .env << EOF
# MusicBrainz Docker Configuration
# Generated by bootstrap.sh on $(date)

# HTTPS/SSL Configuration
MUSICBRAINZ_DOMAIN=$DOMAIN
LETSENCRYPT_EMAIL=$EMAIL

# MusicBrainz URL Configuration
MUSICBRAINZ_WEB_SERVER_HOST=$DOMAIN
MUSICBRAINZ_WEB_SERVER_PORT=443

# Compose file chain (loads OHF optimizations)
COMPOSE_FILE=docker-compose.yml:compose/replication-cron.yml:local/docker-compose.ohf.yml
EOF

echo -e "${GREEN}✓${NC} Created .env configuration file"

# Step 4: Summary and next steps
echo ""
echo "================================================="
echo "Setup Complete!"
echo "================================================="
echo ""
echo "Installation directory: $INSTALL_DIR"
echo "Domain: $DOMAIN"
echo "Email: $EMAIL"
echo ""
echo "Directory structure:"
echo "  $INSTALL_DIR/"
echo "  ├── docker-compose.yml"
echo "  ├── .env"
echo "  └── local/"
echo "      ├── docker-compose.ohf.yml"
echo "      ├── install.sh"
echo "      └── config/"
echo ""

# Ask to run install script
echo "The install script (for Ubuntu servers) will:"
echo "  - Configure UFW firewall"
echo "  - Apply system optimizations"
echo "  - Optionally start services"
echo ""
echo -e "${YELLOW}Note: install.sh is designed for Ubuntu servers.${NC}"
echo "If you're setting this up locally to deploy elsewhere, skip this step."
echo ""
read -p "Run the installation script now? (requires sudo, Ubuntu only) (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo ""
    sudo "$INSTALL_DIR/local/install.sh"
fi

echo ""
echo "================================================="
echo "Next Steps"
echo "================================================="
echo ""
echo "1. Ensure DNS A record points $DOMAIN to your server"
echo ""
echo "2. If deploying to a remote Ubuntu server, copy the files and run:"
echo "   cd $INSTALL_DIR"
echo "   sudo ./local/install.sh"
echo ""
echo "3. Or start services directly (skip install.sh for non-Ubuntu):"
echo "   cd $INSTALL_DIR"
echo "   docker compose up -d"
echo ""
echo "4. Monitor certificate generation:"
echo "   docker logs acme-companion -f"
echo ""

echo "For documentation, see:"
echo "  - $INSTALL_DIR/local/README.md"
echo "  - $INSTALL_DIR/local/OHF_SETUP.md"
echo ""
